a="Rintu" #print("Name:Rintu")
print(a)
age=36
print("age",age)
c="Female"#print("Gender:Female")
print(c)
#print(a,b,c)
name=input("Enter your name:")
print(name)
School=input("Enter the school name:")
print(School)
Grade=input("Enter your grade:")
print(Grade)
Mark=input("Enter the mark:")
print(Mark)
Score=int(input("Enter the score:"))
